version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/app:rw
      - .container-bash-history:/home/appuser/.bash_history:delegated
    ports:
     - 8000:8000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_ADMIN_USER: admin
      DB_ADMIN_PASSWORD: admin
      DB_NAME: maleo
  db:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: django-tutorial
    ports:
      - 5434:5432
    volumes:
      # NOTE: only specifying it explicitly to make it a 'named' volume
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
